### PR TITLE
Updated 16.2

### PR DESCRIPTION
**Pull request by aliasbody**
This PR serves as a base update for the PostgreSQL client. It updates the SDK from 19.08 to 23.08 and PostgreSQL from 12.2 to 16.2 (which is the most up to date LTS version).

### CODE REVIEW

**Comment by aliasbody** [comment]
@p1u3o @dac73 Is this good to be merged? Thank you!

**Comment by maximemoreillon** [comment]
Thanks a lot for this PR! I can't wait to get the update on my machine!

**Comment by dac73** [comment]
@aliasbody can you confirm test build runs?

**Comment by aliasbody** [comment]
@dac73 I haven't rebuild it for a long time, but the version sent is still the build I'm using in my machine. Nothing has changed since so it should build without an issue, (same for pgsql).

**Comment by dac73** [comment]
Ok, approving. The issue is I don't have any machine to test it on. Thanks a lot for the PR 🙏

**Review by dac73 — APPROVED** [review]

**Pull request merged**
